mod data
  provides [Data__Token, Data__Row, Data__Choice, data__mint, data__bytes, data__items, data__add, data__factory, data__id, data__reference]
  uses []
  emits []

brand Data__Token is str rev 1

type Data__Row rev 1 (
  number: int
)

variant Data__Choice<T> rev 1 (
  case Some(value: T)
  case None()
)

fn data__mint(value: str) -> Data__Token rev 1
  emits []
  tests
    a("a") => Ok(seal Data__Token("a"))
    b("b") => Ok(seal Data__Token("b"))
  Ok(seal Data__Token(value))

fn data__bytes(value: Bytes) -> Bytes rev 1
  emits []
  tests
    empty(Bytes(Seq<int>[])) => Ok(Bytes(Seq<int>[]))
    full(Bytes(Seq<int>[0, 255])) => Ok(Bytes(Seq<int>[0, 255]))
  Ok(value)

fn data__items<T>(values: Seq<T>) -> Seq<T> rev 1
  emits []
  tests
    empty<T=int>(Seq<int>[]) => Ok(Seq<int>[])
    ints<T=int>(Seq<int>[7, 9]) => Ok(Seq<int>[7, 9])
    rows<T=Data__Row>(Seq<Data__Row>[Data__Row(7)]) => Ok(Seq<Data__Row>[Data__Row(7)])
  Ok(values)

fn data__add(delta: int, value: int) -> int rev 1
  emits []
  tests
    plus(3, 7) => Ok(10)
    minus(-3, 7) => Ok(4)
  Ok(value + delta)

fn data__id<T>(value: T) -> T rev 1
  emits []
  tests
    empty<T=Bytes>(Bytes(Seq<int>[])) => Ok(Bytes(Seq<int>[]))
    full<T=Bytes>(Bytes(Seq<int>[0, 255])) => Ok(Bytes(Seq<int>[0, 255]))
    a<T=Data__Token>(seal Data__Token("a")) => Ok(seal Data__Token("a"))
    b<T=Data__Token>(seal Data__Token("b")) => Ok(seal Data__Token("b"))
  Ok(value)

fn data__reference<T>() -> Fn<T, T, []> rev 1
  emits []
  tests
    bytes<T=Bytes>() => Ok(fnref data__id<Bytes>())
    token<T=Data__Token>() => Ok(fnref data__id<Data__Token>())
  Ok(fnref data__id<T>())

fn data__factory(delta: int) -> Fn<int, int, []> rev 1
  emits []
  tests
    plus(3) => Ok(fnref data__add(delta = 3))
    minus(-3) => Ok(fnref data__add(delta = -3))
  Ok(fnref data__add(delta = delta))
