package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestMinifyTable(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{
			"line comment",
			"// GENERATED by canlc. DO NOT EDIT.\nexport const x: bigint = 0n;\n",
			"export const x:bigint=0n;",
		},
		{
			"block comment",
			"export /* multi\nline */ const x = 1;",
			"export const x=1;",
		},
		{
			"comment markers inside strings are data",
			"const u = \"http://x\"; // trailing\nconst v = '/*not*/';",
			"const u=\"http://x\";const v='/*not*/';",
		},
		{
			"escaped quotes",
			"const s = \"a\\\"//b\"; const t = 1;",
			"const s=\"a\\\"//b\";const t=1;",
		},
		{
			"keyword before brace and string",
			"case \"ok\": {\nreturn { total: 1 };\n}",
			"case\"ok\":{return{total:1};}",
		},
		{
			"word gap keeps one space",
			"export function count__bump(by: bigint) {",
			"export function count__bump(by:bigint){",
		},
		{
			"minus minus keeps space",
			"const d = a - -b; const e = a - b;",
			"const d=a- -b;const e=a-b;",
		},
		{
			"bigint and dollar identifiers",
			"let Count__total: bigint = 0n;\nconst c = $can_m1;",
			"let Count__total:bigint=0n;const c=$can_m1;",
		},
		{
			"template with expression",
			"const s = `a${x + y}b`; const t = 1;",
			"const s=`a${x+y}b`;const t=1;",
		},
		{
			"template with nested braces and strings",
			"const s = `a${f({k: \"v //\"})}b`;",
			"const s=`a${f({k:\"v //\"})}b`;",
		},
		{
			"empty",
			"",
			"",
		},
		{
			"only comments",
			"// nothing\n/* here */",
			"",
		},
	}
	for _, c := range cases {
		if got := minifyTS(c.in); got != c.want {
			t.Errorf("%s:\n--- got ---\n%s\n--- want ---\n%s", c.name, got, c.want)
		}
		if twice := minifyTS(minifyTS(c.in)); twice != minifyTS(c.in) {
			t.Errorf("%s: not idempotent: %q", c.name, twice)
		}
	}
}

// TestMinifyCounterCompile compiles a real sketch and checks the
// emitted .ts is already minified: no header comment, bigint
// intact, and a minify fixpoint.
func TestMinifyCounterCompile(t *testing.T) {
	dir := t.TempDir()
	if err := compile(dir, []string{"../sketches/counter/counter.can"}); err != nil {
		t.Fatalf("compile: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(dir, "counter.ts"))
	if err != nil {
		t.Fatalf("read counter.ts: %v", err)
	}
	if string(got) != minifyTS(string(got)) {
		t.Errorf("counter.ts is not minified")
	}
	if !strings.Contains(string(got), "0n") {
		t.Errorf("bigint literal lost in minified output")
	}
	if strings.Contains(string(got), "GENERATED") {
		t.Errorf("header comment survived minification")
	}
}
