mod option
  provides [Option__Value, Option__Result, Option__Box, option__value_or, option__some, option__none]
  uses []
  emits []

variant Option__Value<T> rev 1 (
  case Some(value: T)
  case None()
)

type Option__Result<T> rev 1 (
  value: T
)

type Option__Box<T> rev 1 (
  value: Option__Value<T>
)

fn option__value_or<T>(value: Option__Value<T>, alternative: T) -> Option__Result<T> rev 1
  emits []
  tests
    some_int<T=int>(Option__Some<int>(value = 7), 9) => Ok(7)
    none_int<T=int>(Option__None<int>(), 9) => Ok(9)
    some_str<T=str>(Option__Some<str>(value = "present"), "fallback") => Ok("present")
    none_str<T=str>(Option__None<str>(), "fallback") => Ok("fallback")
  match value
    on Option__Some<T> s => Ok(s.value)
    on Option__None<T> _ => Ok(alternative)

fn option__some<T>(value: T) -> Option__Box<T> rev 1
  emits []
  tests
    int_value<T=int>(7) => Ok(Option__Some<int>(value = 7))
    str_value<T=str>("present") => Ok(Option__Some<str>(value = "present"))
  Ok(Option__Some<T>(value = value))

fn option__none<T>(alternative: T) -> Option__Box<T> rev 1
  emits []
  tests
    int_value<T=int>(7) => Ok(Option__None<int>())
    str_value<T=str>("fallback") => Ok(Option__None<str>())
  Ok(Option__None<T>())
